name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v3
      - run: poetry install --with dev
      - run: poetry run pytest --cov=adhs_etl --cov-fail-under=80
      - run: poetry run python -m adhs_etl.cli --month 2025-05 --raw-dir src/tests/fixtures --dry-run
      - name: Benchmark
        run: poetry run python scripts/benchmark.py